spring:
  profiles:
    active: local

  flyway:
    enabled: false
    baseline-on-migrate: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  thymeleaf:
    cache: false