spring:
  profiles:
    active: local

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: update

jasypt:
  encryptor:
    bean: jasyptEncryptor
    password: ${JASYPT_KEY}