spring:
  profiles:
    active: local, auth

  flyway:
    enabled: true
    baseline-on-migrate: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  thymeleaf:
    cache: false

