spring:
  profiles:
    active: local, auth

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate

jasypt:
  encryptor:
    bean: jasyptEncryptor
    password: ${JASYPT_KEY}

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  thymeleaf:
    cache: false

